version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.11-management-alpine
#    networks:
#      - projectiv-network
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  pgdata: